// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hcnoxyfztviuwkiysitm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhjbm94eWZ6dHZpdXdraXlzaXRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NDI5MjgsImV4cCI6MjA2NTUxODkyOH0.nUpvYZmBlKdVlAU3HbuPpXsZfoTFtSgD0guVIskdahc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);