// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htgshzpnenunsdvjndnq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0Z3NoenBuZW51bnNkdmpuZG5xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NzQ4OTQsImV4cCI6MjA2ODU1MDg5NH0.JCZ9oBhcsDo4ceS_j5obBmxmauRdeHSiGuEI09p8CHQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);